-- Fresh isolated Supabase project only. Do not run over the existing workshop database.
begin;
create type public.user_status as enum ('ONLINE', 'OFFLINE');
create table public.users (
  id uuid primary key references auth.users(id),
  username text,
  status public.user_status default 'OFFLINE'
);
create table public.channels (
  id bigint generated by default as identity primary key,
  inserted_at timestamptz not null default now(),
  slug text not null unique,
  created_by uuid not null references public.users(id),
  is_private boolean not null default false
);
create table public.messages (
  id bigint generated by default as identity primary key,
  inserted_at timestamptz not null default now(),
  message text,
  user_id uuid not null references public.users(id),
  channel_id bigint not null references public.channels(id) on delete cascade
);
create table public.channel_members (
  channel_id bigint not null references public.channels(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  primary key (channel_id, user_id)
);
alter table public.users enable row level security;
alter table public.channels enable row level security;
alter table public.messages enable row level security;
alter table public.channel_members enable row level security;
-- Explicit least-privilege grants make fresh setup independent of default grants.
revoke all on public.users, public.channels, public.messages, public.channel_members from anon, authenticated;
grant select on public.users, public.channels, public.channel_members to authenticated;
grant select, insert, update on public.messages to authenticated;
grant usage on sequence public.messages_id_seq to authenticated;
create policy "Signed-in users can read profiles" on public.users
  for select to authenticated using (true);
create policy "Users can read their own memberships" on public.channel_members
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Signed-in users can read channels" on public.channels
  for select to authenticated using (
    not is_private or exists (
      select 1 from public.channel_members cm
      where cm.channel_id = channels.id and cm.user_id = (select auth.uid())
    )
  );
create policy "Signed-in users can read messages" on public.messages
  for select to authenticated using (
    exists (select 1 from public.channels c where c.id = messages.channel_id)
  );
create policy "Users can send messages as themselves" on public.messages
  for insert to authenticated with check (
    (select auth.uid()) = user_id and
    exists (select 1 from public.channels c where c.id = messages.channel_id)
  );
create policy "Users can edit their own messages" on public.messages
  for update to authenticated using (
    (select auth.uid()) = user_id and
    exists (select 1 from public.channels c where c.id = messages.channel_id)
  ) with check (
    (select auth.uid()) = user_id and
    exists (select 1 from public.channels c where c.id = messages.channel_id)
  );
create index messages_channel_history_idx
  on public.messages (channel_id, inserted_at desc, id desc);
alter publication supabase_realtime add table public.messages;
commit;
